[package]
name = "daprs_derive"
version = "0.1.0"
authors = ["Jack Wright <ayax79@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "^1.0"
quote = "^1.0"
daprs_core = { path = "../daprs_core" }